# Generated by Django 5.2.5 on 2025-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('cereal', 'Cereal'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('pulse', 'Pulse'), ('seed', 'Seed')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_kg', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('farmer_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
        ),
    ]
