# Generated by Django 5.2.5 on 2025-08-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='id',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='quantity_kg',
        ),
        migrations.AddField(
            model_name='crop',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
