# Generated by Django 5.2.5 on 2025-08-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_signup_remove_crop_userid_crop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='id',
        ),
        migrations.AddField(
            model_name='crop',
            name='cropid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
