# Generated by Django 5.2.5 on 2025-08-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_remove_crop_id_crop_cropid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(default='crops/image7.jpg', upload_to='crops/'),
        ),
    ]
