# Generated by Django 5.2.5 on 2025-08-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_alter_signup_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='role',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('Buyer', 'Buyer')], default='Farmer', max_length=10),
        ),
    ]
